version: '3'
services:
#######################################
# Setup server container
#######################################
  server:
    build: ./server
    environment:
      - API_HOST:${API_HOST}
      - APP_SERVER_PORT:${APP_SERVER_PORT}
    expose:
      - ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ./server:/foo

#######################################
# Setup client container
#######################################
  client:
    build: ./client
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./client/src:/srv/app/foo_client/src
      - ./client/public:/srv/app/foo_client/public
    links:
      - server
    command: npm run start
