version: '3'
#######################################
# Setup client container
#######################################
services:
  client:
    build: ./client
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./client/src:/srv/app/foo_client/src
      - ./client/public:/srv/app/foo_client/public
    #links:
      #- server
    command: npm run start
